#include "scripts.h"

// docling_install.sh 内容
const char* DOCLING_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# 将环境名称定义为常量\n"
    "APP=\"docling\"\n"
    "\n"
    "# 网络加速\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 更新软件包列表\n"
    "apt update\n"
    "apt-get update && apt-get install -y libxtst6 libxrender1 libxi6 socat \n"
    "\n"
    "# 配置conda环境\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# 创建并激活conda环境\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n $APP python=3.10 -y\n"
    "conda activate $APP\n"
    "\n"
    "\n"
    "# Clone repository\n"
    "cd $HOME\n"
    "rm -rf $APP\n"
    "git clone https://github.com/liangnan93u16/docling_ui.git $APP\n"
    "cd $APP\n"
    "\n"
    "pip install -r requirements.txt";

// docling_start.sh 内容
const char* DOCLING_START = 
    "#!/bin/bash\n"
    "\n"
    "# 将环境名称定义为常量\n"
    "APP=\"docling\"\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate $APP || {\n"
    "    echo \"Error: Failed to activate conda environment '$APP'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "DEVICE=\"cuda\"\n"
    "\n"
    "cd $HOME/$APP\n"
    "streamlit run docling_ui.py --server.port 6006";

