#include "scripts.h"

// manim_install.sh 内容
const char* MANIM_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 安装系统依赖\n"
    "apt update\n"
    "apt install build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg -y\n"
    "apt install texlive texlive-latex-extra -y\n"
    "\n"
    "# Ensure script is run with bash\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 初始化 conda\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# 创建环境时移除 solver 参数\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n manim python=3.10 -y\n"
    "conda activate manim\n"
    "\n"
    "pip install manim ";

// manim_start.sh 内容
const char* MANIM_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate manim || {\n"
    "    echo \"Error: Failed to activate conda environment 'manim'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 创建项目目录\n"
    "mkdir -p $HOME/project\n"
    "cd $HOME/project\n"
    "\n"
    "# 创建 scene.py 文件\n"
    "cat > scene.py << 'EOF'\n"
    "from manim import *\n"
    "\n"
    "class CreateCircle(Scene):\n"
    "    def construct(self):\n"
    "        circle = Circle()  # create a circle\n"
    "        circle.set_fill(PINK, opacity=0.5)  # set the color and transparency\n"
    "        self.play(Create(circle))  # show the circle on screen\n"
    "EOF\n"
    "\n"
    "# manim -pql scene.py CreateCircle\n"
    "manim scene.py CreateCircle\n"
    "\n"
    "echo \"完成一个简单的动画，请查看目录(/root/project/media/videos/scene/1080p60/CreateCircle.mp4)下的视频文件\"\n"
    "";

