#include "scripts.h"

// parsexfrontend_start.sh 内容
const char* PARSEXFRONTEND_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "conda activate parsex-frontend || {\n"
    "    echo \"Error: Failed to activate conda environment 'parsex-frontend'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# 进入项目目录\n"
    "cd $HOME/parsex-frontend\n"
    "\n"
    "# 更新 browserslist 数据库 (修改为新的命令)\n"
    "echo \"Updating browserslist database...\"\n"
    "# npx update-browserslist-db@latest -y\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 设置端口为6006\n"
    "export PORT=6006\n"
    "\n"
    "# 启动项目\n"
    "NODE_OPTIONS=--openssl-legacy-provider yarn start\n"
    "";

// parsexfrontend_install.sh 内容
const char* PARSEXFRONTEND_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Install system dependencies\n"
    "apt update\n"
    "# Install Node.js and npm\n"
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -\n"
    "apt install -y nodejs jq\n"
    "\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n parsex-frontend python=3.10 -y \n"
    "conda activate parsex-frontend \n"
    "\n"
    "# Clone repository and enter directory\n"
    "cd $HOME\n"
    "rm -rf parsex-frontend\n"
    "git clone https://github.com/intsig-textin/parsex-frontend.git parsex-frontend\n"
    "cd parsex-frontend\n"
    "\n"
    "unset http_proxy && unset https_proxy\n"
    "npm config set strict-ssl false\n"
    "npm config set registry https://registry.npmmirror.com\n"
    "npm install -g yarn\n"
    "\n"
    "yarn config set strict-ssl false\n"
    "yarn config set registry https://registry.npmmirror.com # 切换到淘宝镜像\n"
    "# 或者使用以下镜像\n"
    "# yarn config set registry https://registry.npm.taobao.org\n"
    "\n"
    "yarn install\n"
    "yarn upgrade caniuse-lite browserlist\n"
    "";

