#include "scripts.h"

// surya_install.sh 内容
const char* SURYA_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# 将环境名称定义为常量\n"
    "APP=\"surya\"\n"
    "\n"
    "# 网络加速\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 更新软件包列表\n"
    "apt update\n"
    "apt-get update && apt-get install -y libxtst6 libxrender1 libxi6 socat \n"
    "\n"
    "# 配置conda环境\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# 创建并激活conda环境\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n $APP python=3.10 -y\n"
    "conda activate $APP\n"
    "\n"
    "# Clone repository\n"
    "cd $HOME\n"
    "rm -rf $APP\n"
    "git clone https://github.com/VikParuchuri/surya $APP\n"
    "cd $APP\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121\n"
    "\n"
    "# Install core dependencies\n"
    "pip install numpy>=2.1.3\n"
    "pip install opencv-python>=4.10.0\n"
    "pip install pandas>=2.2.3\n"
    "pip install Pillow>=10.0.0\n"
    "pip install onnxruntime>=1.20.0\n"
    "pip install pypdfium2>=4.0.0\n"
    "pip install streamlit>=1.24.0\n"
    "\n"
    "# Install additional dependencies\n"
    "pip install transformers>=4.41.0\n"
    "pip install pydantic>=2.5.3\n"
    "pip install pydantic-settings>=2.1.0\n"
    "pip install python-dotenv>=1.0.0\n"
    "pip install pillow>=10.2.0\n"
    "pip install pypdfium2>=4.25.0\n"
    "pip install opencv-python>=4.9.0.80\n"
    "pip install tabulate>=0.9.0\n"
    "pip install filetype>=1.2.0\n"
    "pip install ftfy>=6.1.3\n"
    "pip install pdftext>=0.3.18\n"
    "\n"
    "# Install GUI dependencies\n"
    "pip install streamlit>=1.31.0\n"
    "\n"
    "# Install optional dependencies\n"
    "pip install pytesseract>=0.3.13  # For benchmarking\n"
    "pip install pymupdf>=1.23.8  # For development\n"
    "pip install datasets>=2.16.1  # For development\n"
    "pip install rapidfuzz>=3.6.1  # For development\n"
    "pip install arabic-reshaper>=3.0.0  # For development\n"
    "\n"
    "# Install project requirements\n"
    "pip install -e .\n"
    "\n"
    "# 下载 ocr_app_zh.py\n"
    "curl -o ocr_app_zh.py https://raw.githubusercontent.com/liangnan93u16/autodl/refs/heads/main/surya/ocr_app_zh.py\n"
    "";

// surya_start.sh 内容
const char* SURYA_START = 
    "#!/bin/bash\n"
    "\n"
    "# 将环境名称定义为常量\n"
    "APP=\"surya\"\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate $APP || {\n"
    "    echo \"Error: Failed to activate conda environment '$APP'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "DEVICE=\"cuda\"\n"
    "\n"
    "cd $HOME/$APP\n"
    "streamlit run ocr_app_zh.py --server.port 6006";

