#include "scripts.h"

// lorascripts_install.sh 内容
const char* LORASCRIPTS_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Ensure script is run with bash\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# Install system dependencies\n"
    "apt update\n"
    "apt install -y portaudio19-dev python3-pyaudio\n"
    "\n"
    "# Configure conda\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n lora-scripts python=3.10 -y\n"
    "conda activate lora-scripts\n"
    "\n"
    "# Clone repository and enter directory\n"
    "cd $HOME\n"
    "rm -rf lora-scripts\n"
    "git clone --recurse-submodules https://github.com/Akegarasu/lora-scripts lora-scripts\n"
    "cd lora-scripts\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.0+cu118 torchvision==0.19.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118\n"
    "pip install --no-deps xformers==0.0.27.post2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118\n"
    "\n"
    "cd $HOME/lora-scripts\n"
    "pip install --upgrade -r requirements.txt";

// lorascripts_start.sh 内容
const char* LORASCRIPTS_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda create -n lora-scripts python=3.10 -y\n"
    "conda activate lora-scripts\n"
    "\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "DEVICE=\"cuda\"\n"
    "\n"
    "# 运行应用\n"
    "cd $HOME/lora-scripts\n"
    "export HF_HOME=huggingface\n"
    "export PYTHONUTF8=1\n"
    "\n"
    "python gui.py \"$@\" --port 6006";

