#include "scripts.h"

// e2-f5-tts_start.sh 内容
const char* E2_F5_TTS_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate e2-f5-tts || {\n"
    "    echo \"Error: Failed to activate conda environment 'e2-f5-tts'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "DEVICE=\"cuda\"\n"
    "\n"
    "# 运行应用\n"
    "cd $HOME/e2-f5-tts/\n"
    "f5-tts_infer-gradio --port 6006 --host 0.0.0.0";

// e2-f5-tts_install.sh 内容
const char* E2_F5_TTS_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Ensure script is run with bash\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# Install system dependencies\n"
    "apt update\n"
    "apt install -y portaudio19-dev python3-pyaudio\n"
    "\n"
    "# Configure conda\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n e2-f5-tts python=3.10 -y\n"
    "conda activate e2-f5-tts\n"
    "\n"
    "# Clone repository and enter directory\n"
    "cd $HOME\n"
    "rm -rf e2-f5-tts\n"
    "git clone https://github.com/SWivid/F5-TTS e2-f5-tts\n"
    "# 进入工作目录\n"
    "cd $HOME/e2-f5-tts/src/f5_tts/infer\n"
    "curl -o infer_gradio.py https://raw.githubusercontent.com/liangnan93u16/autodl/refs/heads/main/e2-f5-tts/infer_gradio.py\n"
    "\n"
    "cd $HOME/e2-f5-tts\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121\n"
    "\n"
    "# Install project and additional dependencies\n"
    "pip install -e .\n"
    "\n"
    "";

