#include "scripts.h"

// applio_start.sh 内容
const char* APPLIO_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate applio || {\n"
    "    echo \"Error: Failed to activate conda environment 'applio'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 运行应用\n"
    "cd $HOME/applio/\n"
    "python app.py --port 6006";

// applio_install.sh 内容
const char* APPLIO_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Fix apt hash sum mismatch issues\n"
    "sudo rm -rf /var/lib/apt/lists/*\n"
    "sudo mkdir -p /etc/gcrypt\n"
    "sudo echo all >> /etc/gcrypt/hwf.deny\n"
    "\n"
    "# Update package lists\n"
    "apt-get update || {\n"
    "    # If update fails, try switching to main server\n"
    "    sed -i 's/http:\\/\\/[a-z]*\\.archive\\.ubuntu\\.com\\/ubuntu\\//http:\\/\\/archive.ubuntu.com\\/ubuntu\\//g' /etc/apt/sources.list\n"
    "    apt-get update\n"
    "}\n"
    "\n"
    "# Install system dependencies\n"
    "apt-get install -y portaudio19-dev python3-pyaudio\n"
    "\n"
    "# Configure conda\n"
    "source $HOME/miniconda3/etc/profile.d/conda.sh || source $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda create -n applio python=3.10 -y\n"
    "conda activate applio\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121\n"
    "\n"
    "# Install requirements directly\n"
    "pip install pip==23.3\n"
    "pip install wheel\n"
    "pip install PyYAML\n"
    "pip install numpy==1.23.5\n"
    "pip install requests==2.32.0\n"
    "pip install tqdm\n"
    "pip install wget\n"
    "pip install pydantic==2.8.2\n"
    "pip install fastapi==0.112.0\n"
    "pip install starlette==0.37.2\n"
    "\n"
    "# Audio processing\n"
    "pip install ffmpeg-python>=0.2.0\n"
    "pip install faiss-cpu==1.7.3\n"
    "pip install librosa==0.9.2\n"
    "pip install pyworld==0.3.4\n"
    "pip install scipy==1.11.1\n"
    "pip install soundfile==0.12.1\n"
    "pip install praat-parselmouth\n"
    "pip install noisereduce\n"
    "pip install versatile-audio-upscaler\n"
    "pip install pedalboard\n"
    "pip install stftpitchshift\n"
    "\n"
    "# Machine learning and deep learning\n"
    "pip install omegaconf\n"
    "pip install numba\n"
    "pip install torchcrepe==0.0.23\n"
    "pip install torchfcpe\n"
    "pip install einops\n"
    "pip install libf0\n"
    "pip install transformers==4.44.2\n"
    "\n"
    "# Visualization and UI\n"
    "pip install matplotlib==3.7.2\n"
    "pip install tensorboard\n"
    "pip install gradio==4.43.0\n"
    "\n"
    "# Miscellaneous utilities\n"
    "pip install certifi==2023.7.22\n"
    "pip install antlr4-python3-runtime==4.8\n"
    "pip install ffmpy==0.3.1\n"
    "pip install tensorboardX\n"
    "pip install edge-tts==6.1.9\n"
    "pip install pypresence\n"
    "pip install beautifulsoup4\n"
    "pip install flask\n"
    "pip install local-attention\n"
    "\n"
    "# Clone repository\n"
    "cd $HOME\n"
    "git clone https://github.com/IAHispano/Applio applio\n"
    "cd applio\n"
    "git reset --hard 5db5e53ad30cc69007e576d96f85fdd932c9fea8\n"
    "\n"
    "";

