#include "scripts.h"

// bolt_install.sh 内容
const char* BOLT_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Install system dependencies\n"
    "apt update\n"
    "apt install -y portaudio19-dev python3-pyaudio curl\n"
    "\n"
    "# Install Node.js and npm\n"
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -\n"
    "apt install -y nodejs\n"
    "\n"
    "# Verify Node.js and npm installation\n"
    "node --version\n"
    "npm --version\n"
    "\n"
    "# Configure conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n bolt python=3.10 -y || {\n"
    "    echo \"Failed to create conda environment\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# Ensure conda environment is activated successfully\n"
    "conda activate bolt || {\n"
    "    echo \"Failed to activate conda environment\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# Clone repository and enter directory\n"
    "cd $HOME\n"
    "rm -rf bolt  # If the directory already exists, delete it first\n"
    "git clone https://github.com/coleam00/bolt.new-any-llm bolt\n"
    "cd bolt\n"
    "\n"
    "# Install npm dependencies\n"
    "# Configure npm to use Taobao registry\n"
    "echo \"npm config registry.npmmirror.com...\"\n"
    "npm config set registry https://registry.npmmirror.com\n"
    "echo \"unset http_proxy...\"\n"
    "unset http_proxy && unset https_proxy\n"
    "echo $http_proxy\n"
    "echo $https_proxy\n"
    "echo \"Installing npm dependencies...\"\n"
    "npm install\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "# pip install torch==2.1.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu121\n"
    "\n"
    "# Install project and additional dependencies\n"
    "pip install litellm[proxy]";

// bolt_start.sh 内容
const char* BOLT_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate bolt || {\n"
    "    echo \"Error: Failed to activate conda environment 'bolt'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 运行应用\n"
    "cd $HOME/bolt/\n"
    "litellm --config config.yaml\n"
    "# PORT=6006 npm run dev\n"
    "export PORT=6006\n"
    "npm run dev";

