#include "scripts.h"

// fish_speech_install.sh 内容
const char* FISH_SPEECH_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    "source /etc/network_turbo\n"
    "\n"
    "# Ensure script is run with bash\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# Install system dependencies\n"
    "apt-get update\n"
    "apt-get install -y portaudio19-dev python3-pyaudio\n"
    "\n"
    "# Configure conda\n"
    "source $HOME/miniconda3/etc/profile.d/conda.sh || source $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda create -n fish-speech python=3.10 -y\n"
    "conda activate fish-speech\n"
    "\n"
    "# Clone repository and enter directory\n"
    "git clone https://github.com/fishaudio/fish-speech fish-speech\n"
    "cd fish-speech\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121\n"
    "\n"
    "# Install project and additional dependencies\n"
    "pip install -e .\n"
    "pip install cachetools livekit livekit-agents\n"
    "\n"
    "# Download model checkpoints\n"
    "huggingface-cli download fishaudio/fish-speech-1.4 --local-dir checkpoints/fish-speech-1.4\n"
    "";

// fish_speech_start.sh 内容
const char* FISH_SPEECH_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true  # 添加 fallback 以防文件不存在\n"
    "\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# Get the directory where the script is located\n"
    "SCRIPT_DIR=\"$( cd \"$( dirname \"${BASH_SOURCE[0]}\" )\" && pwd )\"\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "eval \"$(conda shell.bash hook)\"\n"
    "\n"
    "# 配置 conda\n"
    "source $HOME/miniconda3/etc/profile.d/conda.sh || source $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate fish-speech\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 创建符号链接确保模型路径正确\n"
    "cd /root/fish-speech/tools\n"
    "ln -sf /root/fish-speech/checkpoints checkpoints\n"
    "\n"
    "# Use the requirements.txt from our scripts directory\n"
    "cp \"$SCRIPT_DIR/fish-speech_webui2.py\" ./fish-speech_webui2.py\n"
    "# 运行应用\n"
    "python fish-speech_webui2.py --device $DEVICE\n"
    "";

// fish_speech_webui2.py 内容
const char* FISH_SPEECH_WEBUI2_PY = 
    "import gc\n"
    "import html\n"
    "import io\n"
    "import os\n"
    "import queue\n"
    "import wave\n"
    "from argparse import ArgumentParser\n"
    "from functools import partial\n"
    "from pathlib import Path\n"
    "\n"
    "import gradio as gr\n"
    "import librosa\n"
    "import numpy as np\n"
    "import pyrootutils\n"
    "import torch\n"
    "from loguru import logger\n"
    "from transformers import AutoTokenizer\n"
    "\n"
    "pyrootutils.setup_root(__file__, indicator=\".project-root\", pythonpath=True)\n"
    "\n"
    "\n"
    "from fish_speech.i18n import i18n\n"
    "from fish_speech.text.chn_text_norm.text import Text as ChnNormedText\n"
    "from fish_speech.utils import autocast_exclude_mps, set_seed\n"
    "from tools.api import decode_vq_tokens, encode_reference\n"
    "from tools.file import AUDIO_EXTENSIONS, list_files\n"
    "from tools.llama.generate import (\n"
    "    GenerateRequest,\n"
    "    GenerateResponse,\n"
    "    WrappedGenerateResponse,\n"
    "    launch_thread_safe_queue,\n"
    ")\n"
    "from tools.vqgan.inference import load_model as load_decoder_model\n"
    "\n"
    "# Make einx happy\n"
    "os.environ[\"EINX_FILTER_TRACEBACK\"] = \"false\"\n"
    "\n"
    "\n"
    "HEADER_MD = f\"\"\"# Fish Speech\n"
    "\n"
    "{i18n(\"A text-to-speech model based on VQ-GAN and Llama developed by [Fish Audio](https://fish.audio).\")}  \n"
    "\n"
    "{i18n(\"You can find the source code [here](https://github.com/fishaudio/fish-speech) and models [here](https://huggingface.co/fishaudio/fish-speech-1.4).\")}  \n"
    "\n"
    "{i18n(\"Related code and weights are released under CC BY-NC-SA 4.0 License.\")}  \n"
    "\n"
    "{i18n(\"We are not responsible for any misuse of the model, please consider your local laws and regulations before using it.\")}  \n"
    "\"\"\"\n"
    "\n"
    "TEXTBOX_PLACEHOLDER = i18n(\"Put your text here.\")\n"
    "SPACE_IMPORTED = False\n"
    "\n"
    "\n"
    "def build_html_error_message(error):\n"
    "    return f\"\"\"\n"
    "    <div style=\"color: red; \n"
    "    font-weight: bold;\">\n"
    "        {html.escape(str(error))}\n"
    "    </div>\n"
    "    \"\"\"\n"
    "\n"
    "\n"
    "@torch.inference_mode()\n"
    "def inference(\n"
    "    text,\n"
    "    enable_reference_audio,\n"
    "    reference_audio,\n"
    "    reference_text,\n"
    "    max_new_tokens,\n"
    "    chunk_length,\n"
    "    top_p,\n"
    "    repetition_penalty,\n"
    "    temperature,\n"
    "    seed=\"0\",\n"
    "    streaming=False,\n"
    "):\n"
    "    if args.max_gradio_length > 0 and len(text) > args.max_gradio_length:\n"
    "        return (\n"
    "            None,\n"
    "            None,\n"
    "            i18n(\"Text is too long, please keep it under {} characters.\").format(\n"
    "                args.max_gradio_length\n"
    "            ),\n"
    "        )\n"
    "\n"
    "    seed = int(seed)\n"
    "    if seed != 0:\n"
    "        set_seed(seed)\n"
    "        logger.warning(f\"set seed: {seed}\")\n"
    "\n"
    "    # Parse reference audio aka prompt\n"
    "    prompt_tokens = encode_reference(\n"
    "        decoder_model=decoder_model,\n"
    "        reference_audio=reference_audio,\n"
    "        enable_reference_audio=enable_reference_audio,\n"
    "    )\n"
    "\n"
    "    # LLAMA Inference\n"
    "    request = dict(\n"
    "        device=decoder_model.device,\n"
    "        max_new_tokens=max_new_tokens,\n"
    "        text=text,\n"
    "        top_p=top_p,\n"
    "        repetition_penalty=repetition_penalty,\n"
    "        temperature=temperature,\n"
    "        compile=args.compile,\n"
    "        iterative_prompt=chunk_length > 0,\n"
    "        chunk_length=chunk_length,\n"
    "        max_length=2048,\n"
    "        prompt_tokens=prompt_tokens if enable_reference_audio else None,\n"
    "        prompt_text=reference_text if enable_reference_audio else None,\n"
    "    )\n"
    "\n"
    "    response_queue = queue.Queue()\n"
    "    llama_queue.put(\n"
    "        GenerateRequest(\n"
    "            request=request,\n"
    "            response_queue=response_queue,\n"
    "        )\n"
    "    )\n"
    "\n"
    "    if streaming:\n"
    "        yield wav_chunk_header(), None, None\n"
    "\n"
    "    segments = []\n"
    "\n"
    "    while True:\n"
    "        result: WrappedGenerateResponse = response_queue.get()\n"
    "        if result.status == \"error\":\n"
    "            yield None, None, build_html_error_message(result.response)\n"
    "            break\n"
    "\n"
    "        result: GenerateResponse = result.response\n"
    "        if result.action == \"next\":\n"
    "            break\n"
    "\n"
    "        with autocast_exclude_mps(\n"
    "            device_type=decoder_model.device.type, dtype=args.precision\n"
    "        ):\n"
    "            fake_audios = decode_vq_tokens(\n"
    "                decoder_model=decoder_model,\n"
    "                codes=result.codes,\n"
    "            )\n"
    "\n"
    "        fake_audios = fake_audios.float().cpu().numpy()\n"
    "        segments.append(fake_audios)\n"
    "\n"
    "        if streaming:\n"
    "            wav_header = wav_chunk_header()\n"
    "            audio_data = (fake_audios * 32768).astype(np.int16).tobytes()\n"
    "            yield wav_header + audio_data, None, None\n"
    "\n"
    "    if len(segments) == 0:\n"
    "        return (\n"
    "            None,\n"
    "            None,\n"
    "            build_html_error_message(\n"
    "                i18n(\"No audio generated, please check the input text.\")\n"
    "            ),\n"
    "        )\n"
    "\n"
    "    # No matter streaming or not, we need to return the final audio\n"
    "    audio = np.concatenate(segments, axis=0)\n"
    "    yield None, (decoder_model.spec_transform.sample_rate, audio), None\n"
    "\n"
    "    if torch.cuda.is_available():\n"
    "        torch.cuda.empty_cache()\n"
    "        gc.collect()\n"
    "\n"
    "\n"
    "inference_stream = partial(inference, streaming=True)\n"
    "\n"
    "n_audios = 4\n"
    "\n"
    "global_audio_list = []\n"
    "global_error_list = []\n"
    "\n"
    "\n"
    "def inference_wrapper(\n"
    "    text,\n"
    "    enable_reference_audio,\n"
    "    reference_audio,\n"
    "    reference_text,\n"
    "    max_new_tokens,\n"
    "    chunk_length,\n"
    "    top_p,\n"
    "    repetition_penalty,\n"
    "    temperature,\n"
    "    seed,\n"
    "    batch_infer_num,\n"
    "):\n"
    "    audios = []\n"
    "    errors = []\n"
    "\n"
    "    for _ in range(batch_infer_num):\n"
    "        result = inference(\n"
    "            text,\n"
    "            enable_reference_audio,\n"
    "            reference_audio,\n"
    "            reference_text,\n"
    "            max_new_tokens,\n"
    "            chunk_length,\n"
    "            top_p,\n"
    "            repetition_penalty,\n"
    "            temperature,\n"
    "            seed,\n"
    "        )\n"
    "\n"
    "        _, audio_data, error_message = next(result)\n"
    "\n"
    "        audios.append(\n"
    "            gr.Audio(value=audio_data if audio_data else None, visible=True),\n"
    "        )\n"
    "        errors.append(\n"
    "            gr.HTML(value=error_message if error_message else None, visible=True),\n"
    "        )\n"
    "\n"
    "    for _ in range(batch_infer_num, n_audios):\n"
    "        audios.append(\n"
    "            gr.Audio(value=None, visible=False),\n"
    "        )\n"
    "        errors.append(\n"
    "            gr.HTML(value=None, visible=False),\n"
    "        )\n"
    "\n"
    "    return None, *audios, *errors\n"
    "\n"
    "\n"
    "def wav_chunk_header(sample_rate=44100, bit_depth=16, channels=1):\n"
    "    buffer = io.BytesIO()\n"
    "\n"
    "    with wave.open(buffer, \"wb\") as wav_file:\n"
    "        wav_file.setnchannels(channels)\n"
    "        wav_file.setsampwidth(bit_depth // 8)\n"
    "        wav_file.setframerate(sample_rate)\n"
    "\n"
    "    wav_header_bytes = buffer.getvalue()\n"
    "    buffer.close()\n"
    "    return wav_header_bytes\n"
    "\n"
    "\n"
    "def normalize_text(user_input, use_normalization):\n"
    "    if use_normalization:\n"
    "        return ChnNormedText(raw_text=user_input).normalize()\n"
    "    else:\n"
    "        return user_input\n"
    "\n"
    "\n"
    "def update_examples():\n"
    "    examples_dir = Path(\"references\")\n"
    "    examples_dir.mkdir(parents=True, exist_ok=True)\n"
    "    example_audios = list_files(examples_dir, AUDIO_EXTENSIONS, recursive=True)\n"
    "    return gr.Dropdown(choices=example_audios + [\"\"])\n"
    "\n"
    "\n"
    "def build_app():\n"
    "    with gr.Blocks(theme=gr.themes.Base()) as app:\n"
    "        gr.Markdown(HEADER_MD)\n"
    "\n"
    "        # Use light theme by default\n"
    "        app.load(\n"
    "            None,\n"
    "            None,\n"
    "            js=\"() => {const params = new URLSearchParams(window.location.search);if (!params.has('__theme')) {params.set('__theme', '%s');window.location.search = params.toString();}}\"\n"
    "            % args.theme,\n"
    "        )\n"
    "\n"
    "        # Inference\n"
    "        with gr.Row():\n"
    "            with gr.Column(scale=3):\n"
    "                text = gr.Textbox(\n"
    "                    label=i18n(\"Input Text\"), placeholder=TEXTBOX_PLACEHOLDER, lines=10\n"
    "                )\n"
    "                refined_text = gr.Textbox(\n"
    "                    label=i18n(\"Realtime Transform Text\"),\n"
    "                    placeholder=i18n(\n"
    "                        \"Normalization Result Preview (Currently Only Chinese)\"\n"
    "                    ),\n"
    "                    lines=5,\n"
    "                    interactive=False,\n"
    "                )\n"
    "\n"
    "                with gr.Row():\n"
    "                    if_refine_text = gr.Checkbox(\n"
    "                        label=i18n(\"Text Normalization\"),\n"
    "                        value=False,\n"
    "                        scale=1,\n"
    "                    )\n"
    "\n"
    "                with gr.Row():\n"
    "                    with gr.Column():\n"
    "                        with gr.Tab(label=i18n(\"Advanced Config\")):\n"
    "                            with gr.Row():\n"
    "                                chunk_length = gr.Slider(\n"
    "                                    label=i18n(\"Iterative Prompt Length, 0 means off\"),\n"
    "                                    minimum=50,\n"
    "                                    maximum=300,\n"
    "                                    value=200,\n"
    "                                    step=8,\n"
    "                                )\n"
    "\n"
    "                                max_new_tokens = gr.Slider(\n"
    "                                    label=i18n(\n"
    "                                        \"Maximum tokens per batch, 0 means no limit\"\n"
    "                                    ),\n"
    "                                    minimum=0,\n"
    "                                    maximum=2048,\n"
    "                                    value=0,  # 0 means no limit\n"
    "                                    step=8,\n"
    "                                )\n"
    "\n"
    "                            with gr.Row():\n"
    "                                top_p = gr.Slider(\n"
    "                                    label=\"Top-P\",\n"
    "                                    minimum=0.6,\n"
    "                                    maximum=0.9,\n"
    "                                    value=0.7,\n"
    "                                    step=0.01,\n"
    "                                )\n"
    "\n"
    "                                repetition_penalty = gr.Slider(\n"
    "                                    label=i18n(\"Repetition Penalty\"),\n"
    "                                    minimum=1,\n"
    "                                    maximum=1.5,\n"
    "                                    value=1.2,\n"
    "                                    step=0.01,\n"
    "                                )\n"
    "\n"
    "                            with gr.Row():\n"
    "                                temperature = gr.Slider(\n"
    "                                    label=\"Temperature\",\n"
    "                                    minimum=0.6,\n"
    "                                    maximum=0.9,\n"
    "                                    value=0.7,\n"
    "                                    step=0.01,\n"
    "                                )\n"
    "                                seed = gr.Textbox(\n"
    "                                    label=\"Seed\",\n"
    "                                    info=\"0 means randomized inference, otherwise deterministic\",\n"
    "                                    placeholder=\"any 32-bit-integer\",\n"
    "                                    value=\"0\",\n"
    "                                )\n"
    "\n"
    "                        with gr.Tab(label=i18n(\"Reference Audio\")):\n"
    "                            with gr.Row():\n"
    "                                gr.Markdown(\n"
    "                                    i18n(\n"
    "                                        \"5 to 10 seconds of reference audio, useful for specifying speaker.\"\n"
    "                                    )\n"
    "                                )\n"
    "                            with gr.Row():\n"
    "                                enable_reference_audio = gr.Checkbox(\n"
    "                                    label=i18n(\"Enable Reference Audio\"),\n"
    "                                )\n"
    "\n"
    "                            with gr.Row():\n"
    "                                example_audio_dropdown = gr.Dropdown(\n"
    "                                    label=i18n(\"Select Example Audio\"),\n"
    "                                    choices=[\"\"],\n"
    "                                    value=\"\",\n"
    "                                    interactive=True,\n"
    "                                    allow_custom_value=True,\n"
    "                                )\n"
    "                            with gr.Row():\n"
    "                                reference_audio = gr.Audio(\n"
    "                                    label=i18n(\"Reference Audio\"),\n"
    "                                    type=\"filepath\",\n"
    "                                )\n"
    "                            with gr.Row():\n"
    "                                reference_text = gr.Textbox(\n"
    "                                    label=i18n(\"Reference Text\"),\n"
    "                                    lines=1,\n"
    "                                    placeholder=\"在一无所知中，梦里的一天结束了，一个新的「轮回」便会开始。\",\n"
    "                                    value=\"\",\n"
    "                                )\n"
    "                        with gr.Tab(label=i18n(\"Batch Inference\")):\n"
    "                            with gr.Row():\n"
    "                                batch_infer_num = gr.Slider(\n"
    "                                    label=\"Batch infer nums\",\n"
    "                                    minimum=1,\n"
    "                                    maximum=n_audios,\n"
    "                                    step=1,\n"
    "                                    value=1,\n"
    "                                )\n"
    "\n"
    "            with gr.Column(scale=3):\n"
    "                for _ in range(n_audios):\n"
    "                    with gr.Row():\n"
    "                        error = gr.HTML(\n"
    "                            label=i18n(\"Error Message\"),\n"
    "                            visible=True if _ == 0 else False,\n"
    "                        )\n"
    "                        global_error_list.append(error)\n"
    "                    with gr.Row():\n"
    "                        audio = gr.Audio(\n"
    "                            label=i18n(\"Generated Audio\"),\n"
    "                            type=\"numpy\",\n"
    "                            interactive=False,\n"
    "                            visible=True if _ == 0 else False,\n"
    "                        )\n"
    "                        global_audio_list.append(audio)\n"
    "\n"
    "                with gr.Row():\n"
    "                    stream_audio = gr.Audio(\n"
    "                        label=i18n(\"Streaming Audio\"),\n"
    "                        streaming=True,\n"
    "                        autoplay=True,\n"
    "                        interactive=False,\n"
    "                        show_download_button=True,\n"
    "                    )\n"
    "                with gr.Row():\n"
    "                    with gr.Column(scale=3):\n"
    "                        generate = gr.Button(\n"
    "                            value=\"\\U0001F3A7 \" + i18n(\"Generate\"), variant=\"primary\"\n"
    "                        )\n"
    "                        generate_stream = gr.Button(\n"
    "                            value=\"\\U0001F3A7 \" + i18n(\"Streaming Generate\"),\n"
    "                            variant=\"primary\",\n"
    "                        )\n"
    "\n"
    "        text.input(\n"
    "            fn=normalize_text, inputs=[text, if_refine_text], outputs=[refined_text]\n"
    "        )\n"
    "\n"
    "        def select_example_audio(audio_path):\n"
    "            audio_path = Path(audio_path)\n"
    "            if audio_path.is_file():\n"
    "                lab_file = Path(audio_path.with_suffix(\".lab\"))\n"
    "\n"
    "                if lab_file.exists():\n"
    "                    lab_content = lab_file.read_text(encoding=\"utf-8\").strip()\n"
    "                else:\n"
    "                    lab_content = \"\"\n"
    "\n"
    "                return str(audio_path), lab_content, True\n"
    "            return None, \"\", False\n"
    "\n"
    "        # Connect the dropdown to update reference audio and text\n"
    "        example_audio_dropdown.change(\n"
    "            fn=update_examples, inputs=[], outputs=[example_audio_dropdown]\n"
    "        ).then(\n"
    "            fn=select_example_audio,\n"
    "            inputs=[example_audio_dropdown],\n"
    "            outputs=[reference_audio, reference_text, enable_reference_audio],\n"
    "        )\n"
    "\n"
    "        # # Submit\n"
    "        generate.click(\n"
    "            inference_wrapper,\n"
    "            [\n"
    "                refined_text,\n"
    "                enable_reference_audio,\n"
    "                reference_audio,\n"
    "                reference_text,\n"
    "                max_new_tokens,\n"
    "                chunk_length,\n"
    "                top_p,\n"
    "                repetition_penalty,\n"
    "                temperature,\n"
    "                seed,\n"
    "                batch_infer_num,\n"
    "            ],\n"
    "            [stream_audio, *global_audio_list, *global_error_list],\n"
    "            concurrency_limit=1,\n"
    "        )\n"
    "\n"
    "        generate_stream.click(\n"
    "            inference_stream,\n"
    "            [\n"
    "                refined_text,\n"
    "                enable_reference_audio,\n"
    "                reference_audio,\n"
    "                reference_text,\n"
    "                max_new_tokens,\n"
    "                chunk_length,\n"
    "                top_p,\n"
    "                repetition_penalty,\n"
    "                temperature,\n"
    "                seed,\n"
    "            ],\n"
    "            [stream_audio, global_audio_list[0], global_error_list[0]],\n"
    "            concurrency_limit=1,\n"
    "        )\n"
    "    return app\n"
    "\n"
    "\n"
    "def parse_args():\n"
    "    parser = ArgumentParser()\n"
    "    parser.add_argument(\n"
    "        \"--llama-checkpoint-path\",\n"
    "        type=Path,\n"
    "        default=\"checkpoints/fish-speech-1.4\",\n"
    "    )\n"
    "    parser.add_argument(\n"
    "        \"--decoder-checkpoint-path\",\n"
    "        type=Path,\n"
    "        default=\"checkpoints/fish-speech-1.4/firefly-gan-vq-fsq-8x1024-21hz-generator.pth\",\n"
    "    )\n"
    "    parser.add_argument(\"--decoder-config-name\", type=str, default=\"firefly_gan_vq\")\n"
    "    parser.add_argument(\"--device\", type=str, default=\"cuda\")\n"
    "    parser.add_argument(\"--half\", action=\"store_true\")\n"
    "    parser.add_argument(\"--compile\", action=\"store_true\")\n"
    "    parser.add_argument(\"--max-gradio-length\", type=int, default=0)\n"
    "    parser.add_argument(\"--theme\", type=str, default=\"light\")\n"
    "\n"
    "    return parser.parse_args()\n"
    "\n"
    "\n"
    "if __name__ == \"__main__\":\n"
    "    args = parse_args()\n"
    "    args.precision = torch.half if args.half else torch.bfloat16\n"
    "\n"
    "    logger.info(\"Loading Llama model...\")\n"
    "    llama_queue = launch_thread_safe_queue(\n"
    "        checkpoint_path=args.llama_checkpoint_path,\n"
    "        device=args.device,\n"
    "        precision=args.precision,\n"
    "        compile=args.compile,\n"
    "    )\n"
    "    logger.info(\"Llama model loaded, loading VQ-GAN model...\")\n"
    "\n"
    "    decoder_model = load_decoder_model(\n"
    "        config_name=args.decoder_config_name,\n"
    "        checkpoint_path=args.decoder_checkpoint_path,\n"
    "        device=args.device,\n"
    "    )\n"
    "\n"
    "    logger.info(\"Decoder model loaded, warming up...\")\n"
    "\n"
    "    # Dry run to check if the model is loaded correctly and avoid the first-time latency\n"
    "    list(\n"
    "        inference(\n"
    "            text=\"Hello, world!\",\n"
    "            enable_reference_audio=False,\n"
    "            reference_audio=None,\n"
    "            reference_text=\"\",\n"
    "            max_new_tokens=0,\n"
    "            chunk_length=200,\n"
    "            top_p=0.7,\n"
    "            repetition_penalty=1.2,\n"
    "            temperature=0.7,\n"
    "        )\n"
    "    )\n"
    "\n"
    "    logger.info(\"Warming up done, launching the web UI...\")\n"
    "\n"
    "    app = build_app()\n"
    "    app.launch(show_api=True, server_port=6006)\n"
    "";

