#include "scripts.h"

// diffusersimagefill_start.sh 内容
const char* DIFFUSERSIMAGEFILL_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# Configure conda\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate diffusers-image-fill || {\n"
    "    echo \"Error: Failed to activate conda environment 'diffusers-image-fill'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 运行应用\n"
    "cd $HOME/diffusers-image-fill/\n"
    "python app.py";

// diffusersimagefill_install.sh 内容
const char* DIFFUSERSIMAGEFILL_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Ensure script is run with bash\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# Install system dependencies\n"
    "apt update\n"
    "apt install -y portaudio19-dev python3-pyaudio\n"
    "\n"
    "# Configure conda\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n diffusers-image-fill python=3.10 -y\n"
    "conda activate diffusers-image-fill\n"
    "\n"
    "# Clone repository and enter directory\n"
    "mkdir -p diffusers-image-fill\n"
    "cd diffusers-image-fill\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.1 torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu121\n"
    "\n"
    "# Install project dependencies directly\n"
    "pip install torch\n"
    "pip install spaces\n"
    "pip install gradio==4.42.0\n"
    "pip install gradio-imageslider\n"
    "pip install numpy==1.26.4\n"
    "pip install transformers\n"
    "pip install accelerate\n"
    "pip install diffusers\n"
    "pip install \"fastapi<0.113.0\"\n"
    "pip install opencv-python\n"
    "pip install devicetorch\n"
    "pip install pillow\n"
    "\n"
    "\n"
    "# 进入工作目录\n"
    "cd $HOME/diffusers-image-fill\n"
    "\n"
    "# 下载 webui2.py\n"
    "curl -o app.py https://raw.githubusercontent.com/liangnan93u16/autodl/refs/heads/main/diffusers-image-fill/app.py\n"
    "curl -o controlnet_union.py https://raw.githubusercontent.com/liangnan93u16/autodl/refs/heads/main/diffusers-image-fill/controlnet_union.py\n"
    "curl -o pipeline_fill_sd_xl.py https://raw.githubusercontent.com/liangnan93u16/autodl/refs/heads/main/diffusers-image-fill/pipeline_fill_sd_xl.py\n"
    "\n"
    "";

