#include "scripts.h"

// diamond_install.sh 内容
const char* DIAMOND_INSTALL = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# Install system dependencies\n"
    "apt update\n"
    "apt install -y portaudio19-dev python3-pyaudio\n"
    "\n"
    "# Configure conda\n"
    ". $HOME/miniconda3/etc/profile.d/conda.sh || . $HOME/anaconda3/etc/profile.d/conda.sh\n"
    "\n"
    "# Create and activate conda environment\n"
    "conda clean --all -y  # 清理所有缓存\n"
    "conda create -n diamond python=3.10 -y\n"
    "conda activate diamond\n"
    "\n"
    "# Clone repository and enter directory\n"
    "git clone https://github.com/eloialonso/diamond diamond\n"
    "cd diamond\n"
    "\n"
    "# Install PyTorch and dependencies\n"
    "pip install torch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1\n"
    "\n"
    "# Install project and additional dependencies\n"
    "pip install -r requirements.txt";

// diamond_start.sh 内容
const char* DIAMOND_START = 
    "#!/bin/bash\n"
    "\n"
    "# Network acceleration\n"
    ". /etc/network_turbo || true\n"
    "\n"
    "# 确保 bash 环境\n"
    "if [ -z \"$BASH_VERSION\" ]; then\n"
    "    exec bash \"$0\" \"$@\"\n"
    "fi\n"
    "\n"
    "# 先进入用户主目录\n"
    "cd $HOME\n"
    "\n"
    "# 初始化 conda\n"
    "if [ -f \"/root/miniconda3/etc/profile.d/conda.sh\" ]; then\n"
    "    . \"/root/miniconda3/etc/profile.d/conda.sh\"\n"
    "else\n"
    "    echo \"Error: Could not find conda installation at /root/miniconda3\"\n"
    "    exit 1\n"
    "fi\n"
    "\n"
    "# 激活 conda 环境\n"
    "conda activate diamond || {\n"
    "    echo \"Error: Failed to activate conda environment 'diamond'\"\n"
    "    exit 1\n"
    "}\n"
    "\n"
    "# 检测 NVIDIA GPU\n"
    "if command -v nvidia-smi &> /dev/null; then\n"
    "    DEVICE=\"cuda\"\n"
    "else\n"
    "    DEVICE=\"cpu\"\n"
    "fi\n"
    "\n"
    "# 进入工作目录\n"
    "cd $HOME/diamond\n"
    "\n"
    "# 运行应用\n"
    "export PYTORCH_ENABLE_MPS_FALLBACK=1\n"
    "export PORT=6006\n"
    "python src/play.py --pretrained";

